name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'New Skills'
    labels:
      - 'skill'
      - 'new-skill'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'refactor'

# Map conventional commit prefixes to labels
autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?:/i'
      - '/^feature(\(.+\))?:/i'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?:/i'
      - '/^bugfix(\(.+\))?:/i'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?:/i'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?:/i'
      - '/^build(\(.+\))?:/i'
      - '/^ci(\(.+\))?:/i'
  - label: 'refactor'
    title:
      - '/^refactor(\(.+\))?:/i'
      - '/^perf(\(.+\))?:/i'
      - '/^style(\(.+\))?:/i'
  - label: 'skill'
    title:
      - '/skill/i'
    files:
      - 'skills/**/*'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'skill'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'documentation'
      - 'chore'
  default: patch

exclude-labels:
  - 'skip-changelog'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
